### ISSUE TITLE
groupId to caliper wrong

### ISSUE THREAD

**Issue by donkon** [rdelbru/SIREn#39] opened 2012-04-21 09:16 UTC
the dependency to caliper is wrong:
dependency to com.google.code.caliper

correct is com.google.caliper

**Comment by rdelbru** [comment] 2012-04-21 17:07
Hi,

Thanks for reporting the issue. I am closing this one as it is a duplicate of issue #36.

Regards

**Closed as completed by rdelbru** 2012-04-21 17:07 UTC
